---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.filippomc.it
  resources:
  - simpledeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.filippomc.it
  resources:
  - simpledeployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps.filippomc.it
  resources:
  - simpledeployments/status
  verbs:
  - get
  - patch
  - update
