# permissions for end users to edit simpledeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deploy-operator
    app.kubernetes.io/managed-by: kustomize
  name: simpledeployment-editor-role
rules:
- apiGroups:
  - apps.filippomc.it
  resources:
  - simpledeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.filippomc.it
  resources:
  - simpledeployments/status
  verbs:
  - get
